---
- name: Configuración básica de servidores
  hosts: servers
  become: yes
  tasks:
    - name: Actualizar caché de apt
      apt:
        update_cache: yes
        cache_valid_time: 
 
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
        install_recommends: no  
 
    - name: Instalar cowsay
      apt:
        name: cowsay
        state: present
        install_recommends: no  
 
    - name: Crear archivo en la máquina remota
      file:
        path: /home/vagrant/archivo.txt
        state: touch
 
    - name: Crear archivo en la máquina remota para copiar
      copy:
        content: "Contenido del archivo"
        dest: /home/vagrant/archivo.txt
 
    - name: Copiar archivo en la máquina remota
      copy:
        src: /home/vagrant/archivo.txt
        dest: /home/vagrant/archivo_copy.txt
        remote_src: yes  
 
    - name: Crear carpeta en la máquina remota
      file:
        path: /home/vagrant/Ravelo_Folder
        state: directory
 
    - name: Iniciar servicio de Apache
      service:
        name: apache2
        state: started
        enabled: yes
 
    - name: Agregar usuario en la máquina remota
      user:
        name: nuevo_usuario
        state: present
        create_home: yes
 
    - name: Crear script en la máquina remota
      copy:
        content: |
          #!/bin/bash
          echo "Marcos M. Ravelo"
        dest: /home/vagrant/script.sh
        mode: '0755'
 
    - name: Ejecutar script en la máquina remota
      command: /home/vagrant/script.sh